### ISSUE TITLE
Feature Request: Toggle Wireless Radio

### ISSUE THREAD

**Issue by haywirephoenix** [JamoDevNich/ClientsAPI-SuperHub3#2]
Hey, amazing work! Are you able to use this to disable and enable the wireless radio? I'd like to be able to toggle it quickly when I'm not using it.

**Comment by JamoDevNich** [comment]
Thanks :grin:. That feature currently isn't available but I'll work on implementing it as soon as I get back. Is there any other functionality you want me to look into?

**Comment by haywirephoenix** [comment]
wow thanks, can't wait to see the results! I guess toggling the guest network would also come in handy. If this works I would love to wrap it in python-for-android for a one click gui. 👍

**Comment by haywirephoenix** [comment]
p.s: the url on mine is           ?wifi_radio&mid=WirelessSignal 
input radio id for 5ghz is          Enable50 and Disable50  
id for 2.4ghz is                          Enable24 and Disable24
and onsubmit it runs            _onclick_1(arguments[0]);

not sure if this is useful as you're the py god

**Comment by JamoDevNich** [comment]
I'm currently in the process of integrating the Wlan toggling functionality - I've almost completed reverse engineering and now in the process of testing. I've also rewritten a portion of the script so it can be controlled via command line arguments, as well as via the interface. Should be done and up in a few hours.

**Comment by JamoDevNich** [comment]
The WLAN toggling features have now been implemented in release 1.0.0, for both private WLAN and guest WLAN.
https://github.com/JamoDevNich/ClientsAPI-SuperHub3/releases/tag/1.0.0

**Comment by haywirephoenix** [comment]
It works, incredible! Thanks!
