### ISSUE TITLE
Staying in the loop

### ISSUE THREAD

**Issue by haywirephoenix** [JamoDevNich/ClientsAPI-SuperHub3#4]
Any advice on how to prevent it from dropping out/exiting after a command is run? It seems like this was the intended behaviour.

**Comment by JamoDevNich** [comment]
It is the intended behaviour, however enclosing the menu in a `while True` loop will prevent it from exiting after running a command.

https://github.com/JamoDevNich/ClientsAPI-SuperHub3/blob/c30efb17489e112b87972fd432ffc20a802d55f4/superhubclientsapi.py#L384-L398

**Comment by haywirephoenix** [comment]
Works great thanks, I also added a os.system('cls') to the menu to keep it tidy.
