### ISSUE TITLE
oid defines for reboot

### ISSUE THREAD

**Issue by jasonchu024** [JamoDevNich/ClientsAPI-SuperHub3#5]
Hi,

I happened to find extra oid defines to reboot the VM SuperHub3, it's been tested OK from me and hope that can be of help if you'd like to improve further. They are:

#to raise reboot command
web(superhub_ip_addr+"/snmpSet?oid=1.3.6.1.4.1.4115.1.20.1.1.5.15.0;"+superhub_req_ext,superhub_cookie_header);  

#to confirm reboot
web(superhub_ip_addr+"/snmpSet?oid=1.3.6.1.2.1.69.1.1.3.0=2;2;"+superhub_req_ext,superhub_cookie_header);

#logout VM 
web(superhub_ip_addr+"/logout?"+superhub_req_ext);

Regards,

JC

**Comment by JamoDevNich** [comment]
Thanks for letting me know - I'll likely implement these as soon as I can.

**Comment by JamoDevNich** [comment]
Both now successfully implemented in release 1.0.2. I haven't tested reboot (yet) though.

https://github.com/JamoDevNich/ClientsAPI-SuperHub3/blob/700259da7d060bccbb579199bca6c0366beee15f/superhubclientsapi.py#L148-L164

Edit: fixing permalink
