### ISSUE TITLE
Modify DNS settings

### ISSUE THREAD

**Issue by haywirephoenix** [JamoDevNich/ClientsAPI-SuperHub3#6]
Did you find anything relating to hidden DNS settings when poking around the superhub3?

**Comment by JamoDevNich** [comment]
It should be possible, considering the main interface tends mask a bit of hidden functionality :thinking:  I'll run some tests and see if it's changeable or not.

**Comment by JamoDevNich** [comment]
I don't think it's possible, as the setting seems to be read-only and won't accept any values.

I also found this [report](https://www.netscylla.com/blog/2019/02/04/Arris-CableModem-SNMP.html) from a pentesting agency which attempted to change the DNS settings too, to no avail.

There is a secondary admin account present on the SH3 called 'upccsr', that account may be able to modify certain read-only values on the router. The password for it isn't known at this time though.
